/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_groovemanager_spi_asio_ASIOSampleType */

#ifndef _Included_com_groovemanager_spi_asio_ASIOSampleType
#define _Included_com_groovemanager_spi_asio_ASIOSampleType
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_groovemanager_spi_asio_ASIOSampleType
 * Method:    ASIOSTInt16MSB
 * Signature: ()J
 */
JNIEXPORT jint JNICALL Java_com_groovemanager_spi_asio_ASIOSampleType_ASIOSTInt16MSB
  (JNIEnv *, jclass);

/*
 * Class:     com_groovemanager_spi_asio_ASIOSampleType
 * Method:    ASIOSTInt24MSB
 * Signature: ()J
 */
JNIEXPORT jint JNICALL Java_com_groovemanager_spi_asio_ASIOSampleType_ASIOSTInt24MSB
  (JNIEnv *, jclass);

/*
 * Class:     com_groovemanager_spi_asio_ASIOSampleType
 * Method:    ASIOSTInt32MSB
 * Signature: ()J
 */
JNIEXPORT jint JNICALL Java_com_groovemanager_spi_asio_ASIOSampleType_ASIOSTInt32MSB
  (JNIEnv *, jclass);

/*
 * Class:     com_groovemanager_spi_asio_ASIOSampleType
 * Method:    ASIOSTFloat32MSB
 * Signature: ()J
 */
JNIEXPORT jint JNICALL Java_com_groovemanager_spi_asio_ASIOSampleType_ASIOSTFloat32MSB
  (JNIEnv *, jclass);

/*
 * Class:     com_groovemanager_spi_asio_ASIOSampleType
 * Method:    ASIOSTFloat64MSB
 * Signature: ()J
 */
JNIEXPORT jint JNICALL Java_com_groovemanager_spi_asio_ASIOSampleType_ASIOSTFloat64MSB
  (JNIEnv *, jclass);

/*
 * Class:     com_groovemanager_spi_asio_ASIOSampleType
 * Method:    ASIOSTInt32MSB16
 * Signature: ()J
 */
JNIEXPORT jint JNICALL Java_com_groovemanager_spi_asio_ASIOSampleType_ASIOSTInt32MSB16
  (JNIEnv *, jclass);

/*
 * Class:     com_groovemanager_spi_asio_ASIOSampleType
 * Method:    ASIOSTInt32MSB18
 * Signature: ()J
 */
JNIEXPORT jint JNICALL Java_com_groovemanager_spi_asio_ASIOSampleType_ASIOSTInt32MSB18
  (JNIEnv *, jclass);

/*
 * Class:     com_groovemanager_spi_asio_ASIOSampleType
 * Method:    ASIOSTInt32MSB20
 * Signature: ()J
 */
JNIEXPORT jint JNICALL Java_com_groovemanager_spi_asio_ASIOSampleType_ASIOSTInt32MSB20
  (JNIEnv *, jclass);

/*
 * Class:     com_groovemanager_spi_asio_ASIOSampleType
 * Method:    ASIOSTInt32MSB24
 * Signature: ()J
 */
JNIEXPORT jint JNICALL Java_com_groovemanager_spi_asio_ASIOSampleType_ASIOSTInt32MSB24
  (JNIEnv *, jclass);

/*
 * Class:     com_groovemanager_spi_asio_ASIOSampleType
 * Method:    ASIOSTInt16LSB
 * Signature: ()J
 */
JNIEXPORT jint JNICALL Java_com_groovemanager_spi_asio_ASIOSampleType_ASIOSTInt16LSB
  (JNIEnv *, jclass);

/*
 * Class:     com_groovemanager_spi_asio_ASIOSampleType
 * Method:    ASIOSTInt24LSB
 * Signature: ()J
 */
JNIEXPORT jint JNICALL Java_com_groovemanager_spi_asio_ASIOSampleType_ASIOSTInt24LSB
  (JNIEnv *, jclass);

/*
 * Class:     com_groovemanager_spi_asio_ASIOSampleType
 * Method:    ASIOSTInt32LSB
 * Signature: ()J
 */
JNIEXPORT jint JNICALL Java_com_groovemanager_spi_asio_ASIOSampleType_ASIOSTInt32LSB
  (JNIEnv *, jclass);

/*
 * Class:     com_groovemanager_spi_asio_ASIOSampleType
 * Method:    ASIOSTFloat32LSB
 * Signature: ()J
 */
JNIEXPORT jint JNICALL Java_com_groovemanager_spi_asio_ASIOSampleType_ASIOSTFloat32LSB
  (JNIEnv *, jclass);

/*
 * Class:     com_groovemanager_spi_asio_ASIOSampleType
 * Method:    ASIOSTFloat64LSB
 * Signature: ()J
 */
JNIEXPORT jint JNICALL Java_com_groovemanager_spi_asio_ASIOSampleType_ASIOSTFloat64LSB
  (JNIEnv *, jclass);

/*
 * Class:     com_groovemanager_spi_asio_ASIOSampleType
 * Method:    ASIOSTInt32LSB16
 * Signature: ()J
 */
JNIEXPORT jint JNICALL Java_com_groovemanager_spi_asio_ASIOSampleType_ASIOSTInt32LSB16
  (JNIEnv *, jclass);

/*
 * Class:     com_groovemanager_spi_asio_ASIOSampleType
 * Method:    ASIOSTInt32LSB18
 * Signature: ()J
 */
JNIEXPORT jint JNICALL Java_com_groovemanager_spi_asio_ASIOSampleType_ASIOSTInt32LSB18
  (JNIEnv *, jclass);

/*
 * Class:     com_groovemanager_spi_asio_ASIOSampleType
 * Method:    ASIOSTInt32LSB20
 * Signature: ()J
 */
JNIEXPORT jint JNICALL Java_com_groovemanager_spi_asio_ASIOSampleType_ASIOSTInt32LSB20
  (JNIEnv *, jclass);

/*
 * Class:     com_groovemanager_spi_asio_ASIOSampleType
 * Method:    ASIOSTInt32LSB24
 * Signature: ()J
 */
JNIEXPORT jint JNICALL Java_com_groovemanager_spi_asio_ASIOSampleType_ASIOSTInt32LSB24
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
