/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_groovemanager_spi_asio_ASIOCallback */

#ifndef _Included_com_groovemanager_spi_asio_ASIOCallback
#define _Included_com_groovemanager_spi_asio_ASIOCallback
#ifdef __cplusplus
extern "C" {
#endif
#undef com_groovemanager_spi_asio_ASIOCallback_MIN_PRIORITY
#define com_groovemanager_spi_asio_ASIOCallback_MIN_PRIORITY 1L
#undef com_groovemanager_spi_asio_ASIOCallback_NORM_PRIORITY
#define com_groovemanager_spi_asio_ASIOCallback_NORM_PRIORITY 5L
#undef com_groovemanager_spi_asio_ASIOCallback_MAX_PRIORITY
#define com_groovemanager_spi_asio_ASIOCallback_MAX_PRIORITY 10L
/*
 * Class:     com_groovemanager_spi_asio_ASIOCallback
 * Method:    checkForCallback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_groovemanager_spi_asio_ASIOCallback_checkForCallback
  (JNIEnv *, jclass);

/*
 * Class:     com_groovemanager_spi_asio_ASIOCallback
 * Method:    releaseLocks
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_groovemanager_spi_asio_ASIOCallback_releaseLocks
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
