/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_groovemanager_spi_asio_ASIOInputMonitor */

#ifndef _Included_com_groovemanager_spi_asio_ASIOInputMonitor
#define _Included_com_groovemanager_spi_asio_ASIOInputMonitor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_groovemanager_spi_asio_ASIOInputMonitor
 * Method:    input
 * Signature: ()J
 */
JNIEXPORT jint JNICALL Java_com_groovemanager_spi_asio_ASIOInputMonitor_input
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_ASIOInputMonitor
 * Method:    output
 * Signature: ()J
 */
JNIEXPORT jint JNICALL Java_com_groovemanager_spi_asio_ASIOInputMonitor_output
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_ASIOInputMonitor
 * Method:    gain
 * Signature: ()J
 */
JNIEXPORT jint JNICALL Java_com_groovemanager_spi_asio_ASIOInputMonitor_gain
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_ASIOInputMonitor
 * Method:    state
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_groovemanager_spi_asio_ASIOInputMonitor_state
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_ASIOInputMonitor
 * Method:    pan
 * Signature: ()J
 */
JNIEXPORT jint JNICALL Java_com_groovemanager_spi_asio_ASIOInputMonitor_pan
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_ASIOInputMonitor
 * Method:    setInput
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_groovemanager_spi_asio_ASIOInputMonitor_setInput
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_groovemanager_spi_asio_ASIOInputMonitor
 * Method:    setOutput
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_groovemanager_spi_asio_ASIOInputMonitor_setOutput
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_groovemanager_spi_asio_ASIOInputMonitor
 * Method:    setGain
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_groovemanager_spi_asio_ASIOInputMonitor_setGain
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_groovemanager_spi_asio_ASIOInputMonitor
 * Method:    setPan
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_groovemanager_spi_asio_ASIOInputMonitor_setPan
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_groovemanager_spi_asio_ASIOInputMonitor
 * Method:    setState
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_groovemanager_spi_asio_ASIOInputMonitor_setState
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_groovemanager_spi_asio_ASIOInputMonitor
 * Method:    createClass
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_groovemanager_spi_asio_ASIOInputMonitor_createClass
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_ASIOInputMonitor
 * Method:    cleanUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_groovemanager_spi_asio_ASIOInputMonitor_cleanUp
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
