/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_groovemanager_spi_asio_ASIOTimeCode */

#ifndef _Included_com_groovemanager_spi_asio_ASIOTimeCode
#define _Included_com_groovemanager_spi_asio_ASIOTimeCode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_groovemanager_spi_asio_ASIOTimeCode
 * Method:    createClass
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_groovemanager_spi_asio_ASIOTimeCode_createClass
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_ASIOTimeCode
 * Method:    cleanUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_groovemanager_spi_asio_ASIOTimeCode_cleanUp
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_ASIOTimeCode
 * Method:    speed
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_groovemanager_spi_asio_ASIOTimeCode_speed
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_ASIOTimeCode
 * Method:    jtimeCodeSamples
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_groovemanager_spi_asio_ASIOTimeCode_jtimeCodeSamples
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_ASIOTimeCode
 * Method:    flags
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_groovemanager_spi_asio_ASIOTimeCode_flags
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_ASIOTimeCode
 * Method:    kTcValid
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_groovemanager_spi_asio_ASIOTimeCode_kTcValid
  (JNIEnv *, jclass);

/*
 * Class:     com_groovemanager_spi_asio_ASIOTimeCode
 * Method:    kTcRunning
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_groovemanager_spi_asio_ASIOTimeCode_kTcRunning
  (JNIEnv *, jclass);

/*
 * Class:     com_groovemanager_spi_asio_ASIOTimeCode
 * Method:    kTcReverse
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_groovemanager_spi_asio_ASIOTimeCode_kTcReverse
  (JNIEnv *, jclass);

/*
 * Class:     com_groovemanager_spi_asio_ASIOTimeCode
 * Method:    kTcOnspeed
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_groovemanager_spi_asio_ASIOTimeCode_kTcOnspeed
  (JNIEnv *, jclass);

/*
 * Class:     com_groovemanager_spi_asio_ASIOTimeCode
 * Method:    kTcStill
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_groovemanager_spi_asio_ASIOTimeCode_kTcStill
  (JNIEnv *, jclass);

/*
 * Class:     com_groovemanager_spi_asio_ASIOTimeCode
 * Method:    kTcSpeedValid
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_groovemanager_spi_asio_ASIOTimeCode_kTcSpeedValid
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
