/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_groovemanager_spi_asio_AsioTimeInfo */

#ifndef _Included_com_groovemanager_spi_asio_AsioTimeInfo
#define _Included_com_groovemanager_spi_asio_AsioTimeInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_groovemanager_spi_asio_AsioTimeInfo
 * Method:    createClass
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_groovemanager_spi_asio_AsioTimeInfo_createClass
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_AsioTimeInfo
 * Method:    cleanUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_groovemanager_spi_asio_AsioTimeInfo_cleanUp
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_AsioTimeInfo
 * Method:    speed
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_groovemanager_spi_asio_AsioTimeInfo_speed
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_AsioTimeInfo
 * Method:    jsystemTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_groovemanager_spi_asio_AsioTimeInfo_jsystemTime
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_AsioTimeInfo
 * Method:    jsamplePosition
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_groovemanager_spi_asio_AsioTimeInfo_jsamplePosition
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_AsioTimeInfo
 * Method:    jsampleRate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_groovemanager_spi_asio_AsioTimeInfo_jsampleRate
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_AsioTimeInfo
 * Method:    flags
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_groovemanager_spi_asio_AsioTimeInfo_flags
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_AsioTimeInfo
 * Method:    kSystemTimeValid
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_groovemanager_spi_asio_AsioTimeInfo_kSystemTimeValid
  (JNIEnv *, jclass);

/*
 * Class:     com_groovemanager_spi_asio_AsioTimeInfo
 * Method:    kSamplePositionValid
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_groovemanager_spi_asio_AsioTimeInfo_kSamplePositionValid
  (JNIEnv *, jclass);

/*
 * Class:     com_groovemanager_spi_asio_AsioTimeInfo
 * Method:    kSampleRateValid
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_groovemanager_spi_asio_AsioTimeInfo_kSampleRateValid
  (JNIEnv *, jclass);

/*
 * Class:     com_groovemanager_spi_asio_AsioTimeInfo
 * Method:    kSpeedValid
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_groovemanager_spi_asio_AsioTimeInfo_kSpeedValid
  (JNIEnv *, jclass);

/*
 * Class:     com_groovemanager_spi_asio_AsioTimeInfo
 * Method:    kSampleRateChanged
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_groovemanager_spi_asio_AsioTimeInfo_kSampleRateChanged
  (JNIEnv *, jclass);

/*
 * Class:     com_groovemanager_spi_asio_AsioTimeInfo
 * Method:    kClockSourceChanged
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_groovemanager_spi_asio_AsioTimeInfo_kClockSourceChanged
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
