/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_groovemanager_spi_asio_ASIOMixer */

#ifndef _Included_com_groovemanager_spi_asio_ASIOMixer
#define _Included_com_groovemanager_spi_asio_ASIOMixer
#ifdef __cplusplus
extern "C" {
#endif
#undef com_groovemanager_spi_asio_ASIOMixer_UNLOADED
#define com_groovemanager_spi_asio_ASIOMixer_UNLOADED 0L
#undef com_groovemanager_spi_asio_ASIOMixer_LOADED
#define com_groovemanager_spi_asio_ASIOMixer_LOADED 1L
#undef com_groovemanager_spi_asio_ASIOMixer_INITIALIZED
#define com_groovemanager_spi_asio_ASIOMixer_INITIALIZED 2L
#undef com_groovemanager_spi_asio_ASIOMixer_PREPARED
#define com_groovemanager_spi_asio_ASIOMixer_PREPARED 3L
#undef com_groovemanager_spi_asio_ASIOMixer_RUNNING
#define com_groovemanager_spi_asio_ASIOMixer_RUNNING 4L
/*
 * Class:     com_groovemanager_spi_asio_ASIOMixer
 * Method:    initVM
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_groovemanager_spi_asio_ASIOMixer_initVM
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_ASIOMixer
 * Method:    freeVM
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_groovemanager_spi_asio_ASIOMixer_freeVM
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_groovemanager_spi_asio_ASIOMixer_CopyBuffersThread */

#ifndef _Included_com_groovemanager_spi_asio_ASIOMixer_CopyBuffersThread
#define _Included_com_groovemanager_spi_asio_ASIOMixer_CopyBuffersThread
#ifdef __cplusplus
extern "C" {
#endif
#undef com_groovemanager_spi_asio_ASIOMixer_CopyBuffersThread_MIN_PRIORITY
#define com_groovemanager_spi_asio_ASIOMixer_CopyBuffersThread_MIN_PRIORITY 1L
#undef com_groovemanager_spi_asio_ASIOMixer_CopyBuffersThread_NORM_PRIORITY
#define com_groovemanager_spi_asio_ASIOMixer_CopyBuffersThread_NORM_PRIORITY 5L
#undef com_groovemanager_spi_asio_ASIOMixer_CopyBuffersThread_MAX_PRIORITY
#define com_groovemanager_spi_asio_ASIOMixer_CopyBuffersThread_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
