/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_groovemanager_spi_asio_ASIOChannelInfo */

#ifndef _Included_com_groovemanager_spi_asio_ASIOChannelInfo
#define _Included_com_groovemanager_spi_asio_ASIOChannelInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_groovemanager_spi_asio_ASIOChannelInfo
 * Method:    channel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_groovemanager_spi_asio_ASIOChannelInfo_channel
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_ASIOChannelInfo
 * Method:    isInput
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_groovemanager_spi_asio_ASIOChannelInfo_isInput
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_ASIOChannelInfo
 * Method:    isActive
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_groovemanager_spi_asio_ASIOChannelInfo_isActive
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_ASIOChannelInfo
 * Method:    channelGroup
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_groovemanager_spi_asio_ASIOChannelInfo_channelGroup
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_ASIOChannelInfo
 * Method:    type
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_groovemanager_spi_asio_ASIOChannelInfo_type
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_ASIOChannelInfo
 * Method:    name
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_groovemanager_spi_asio_ASIOChannelInfo_name
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_ASIOChannelInfo
 * Method:    setChannel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_groovemanager_spi_asio_ASIOChannelInfo_setChannel
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_groovemanager_spi_asio_ASIOChannelInfo
 * Method:    setIsInput
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_groovemanager_spi_asio_ASIOChannelInfo_setIsInput
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_groovemanager_spi_asio_ASIOChannelInfo
 * Method:    createClass
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_groovemanager_spi_asio_ASIOChannelInfo_createClass
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_ASIOChannelInfo
 * Method:    cleanUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_groovemanager_spi_asio_ASIOChannelInfo_cleanUp
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
