/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_groovemanager_spi_asio_ASIOTimeStamp */

#ifndef _Included_com_groovemanager_spi_asio_ASIOTimeStamp
#define _Included_com_groovemanager_spi_asio_ASIOTimeStamp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_groovemanager_spi_asio_ASIOTimeStamp
 * Method:    createClass
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_groovemanager_spi_asio_ASIOTimeStamp_createClass
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_ASIOTimeStamp
 * Method:    cleanUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_groovemanager_spi_asio_ASIOTimeStamp_cleanUp
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_ASIOTimeStamp
 * Method:    doubleValue
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_groovemanager_spi_asio_ASIOTimeStamp_doubleValue
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
