/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_groovemanager_spi_asio_ASIOTime */

#ifndef _Included_com_groovemanager_spi_asio_ASIOTime
#define _Included_com_groovemanager_spi_asio_ASIOTime
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_groovemanager_spi_asio_ASIOTime
 * Method:    createClass
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_groovemanager_spi_asio_ASIOTime_createClass
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_ASIOTime
 * Method:    cleanUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_groovemanager_spi_asio_ASIOTime_cleanUp
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_ASIOTime
 * Method:    jTimeInfo
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_groovemanager_spi_asio_ASIOTime_jTimeInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_ASIOTime
 * Method:    jTimeCode
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_groovemanager_spi_asio_ASIOTime_jTimeCode
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
