/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_groovemanager_spi_asio_ASIODataLine */

#ifndef _Included_com_groovemanager_spi_asio_ASIODataLine
#define _Included_com_groovemanager_spi_asio_ASIODataLine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_groovemanager_spi_asio_ASIODataLine
 * Method:    getAddress
 * Signature: (Ljava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_com_groovemanager_spi_asio_ASIODataLine_getAddress
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_groovemanager_spi_asio_ASIODataLine
 * Method:    deliverData
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_com_groovemanager_spi_asio_ASIODataLine_deliverData
  (JNIEnv *, jobject, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
