/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_groovemanager_spi_asio_ASIOError */

#ifndef _Included_com_groovemanager_spi_asio_ASIOError
#define _Included_com_groovemanager_spi_asio_ASIOError
#ifdef __cplusplus
extern "C" {
#endif
#undef com_groovemanager_spi_asio_ASIOError_serialVersionUID
#define com_groovemanager_spi_asio_ASIOError_serialVersionUID -3042686055658047285i64
#undef com_groovemanager_spi_asio_ASIOError_serialVersionUID
#define com_groovemanager_spi_asio_ASIOError_serialVersionUID -3387516993124229948i64
/*
 * Class:     com_groovemanager_spi_asio_ASIOError
 * Method:    ASE_OK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_groovemanager_spi_asio_ASIOError_ASE_1OK
  (JNIEnv *, jclass);

/*
 * Class:     com_groovemanager_spi_asio_ASIOError
 * Method:    ASE_SUCCESS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_groovemanager_spi_asio_ASIOError_ASE_1SUCCESS
  (JNIEnv *, jclass);

/*
 * Class:     com_groovemanager_spi_asio_ASIOError
 * Method:    ASE_NotPresent
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_groovemanager_spi_asio_ASIOError_ASE_1NotPresent
  (JNIEnv *, jclass);

/*
 * Class:     com_groovemanager_spi_asio_ASIOError
 * Method:    ASE_HWMalfunction
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_groovemanager_spi_asio_ASIOError_ASE_1HWMalfunction
  (JNIEnv *, jclass);

/*
 * Class:     com_groovemanager_spi_asio_ASIOError
 * Method:    ASE_InvalidParameter
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_groovemanager_spi_asio_ASIOError_ASE_1InvalidParameter
  (JNIEnv *, jclass);

/*
 * Class:     com_groovemanager_spi_asio_ASIOError
 * Method:    ASE_InvalidMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_groovemanager_spi_asio_ASIOError_ASE_1InvalidMode
  (JNIEnv *, jclass);

/*
 * Class:     com_groovemanager_spi_asio_ASIOError
 * Method:    ASE_SPNotAdvancing
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_groovemanager_spi_asio_ASIOError_ASE_1SPNotAdvancing
  (JNIEnv *, jclass);

/*
 * Class:     com_groovemanager_spi_asio_ASIOError
 * Method:    ASE_NoClock
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_groovemanager_spi_asio_ASIOError_ASE_1NoClock
  (JNIEnv *, jclass);

/*
 * Class:     com_groovemanager_spi_asio_ASIOError
 * Method:    ASE_NoMemory
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_groovemanager_spi_asio_ASIOError_ASE_1NoMemory
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
