/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_groovemanager_spi_asio_ASIOBufferInfo */

#ifndef _Included_com_groovemanager_spi_asio_ASIOBufferInfo
#define _Included_com_groovemanager_spi_asio_ASIOBufferInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_groovemanager_spi_asio_ASIOBufferInfo
 * Method:    isInput
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_groovemanager_spi_asio_ASIOBufferInfo_isInput
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_ASIOBufferInfo
 * Method:    setIsInput
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_groovemanager_spi_asio_ASIOBufferInfo_setIsInput
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_groovemanager_spi_asio_ASIOBufferInfo
 * Method:    channelNum
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_groovemanager_spi_asio_ASIOBufferInfo_channelNum
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_ASIOBufferInfo
 * Method:    setChannelNum
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_groovemanager_spi_asio_ASIOBufferInfo_setChannelNum
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_groovemanager_spi_asio_ASIOBufferInfo
 * Method:    buffers
 * Signature: ()[J
 */
JNIEXPORT jlongArray JNICALL Java_com_groovemanager_spi_asio_ASIOBufferInfo_buffers
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_ASIOBufferInfo
 * Method:    createClass
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_groovemanager_spi_asio_ASIOBufferInfo_createClass
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_ASIOBufferInfo
 * Method:    cleanUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_groovemanager_spi_asio_ASIOBufferInfo_cleanUp
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
