/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_groovemanager_spi_asio_ASIOClockSource */

#ifndef _Included_com_groovemanager_spi_asio_ASIOClockSource
#define _Included_com_groovemanager_spi_asio_ASIOClockSource
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_groovemanager_spi_asio_ASIOClockSource
 * Method:    index
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_groovemanager_spi_asio_ASIOClockSource_index
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_ASIOClockSource
 * Method:    associatedChannel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_groovemanager_spi_asio_ASIOClockSource_associatedChannel
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_ASIOClockSource
 * Method:    associatedGroup
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_groovemanager_spi_asio_ASIOClockSource_associatedGroup
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_ASIOClockSource
 * Method:    isCurrentSource
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_groovemanager_spi_asio_ASIOClockSource_isCurrentSource
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_ASIOClockSource
 * Method:    name
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_groovemanager_spi_asio_ASIOClockSource_name
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_ASIOClockSource
 * Method:    createClass
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_groovemanager_spi_asio_ASIOClockSource_createClass
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_ASIOClockSource
 * Method:    cleanUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_groovemanager_spi_asio_ASIOClockSource_cleanUp
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
