/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_groovemanager_spi_asio_ASIOSampleRate */

#ifndef _Included_com_groovemanager_spi_asio_ASIOSampleRate
#define _Included_com_groovemanager_spi_asio_ASIOSampleRate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_groovemanager_spi_asio_ASIOSampleRate
 * Method:    createClass
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_groovemanager_spi_asio_ASIOSampleRate_createClass
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_ASIOSampleRate
 * Method:    cleanUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_groovemanager_spi_asio_ASIOSampleRate_cleanUp
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_ASIOSampleRate
 * Method:    doubleValue
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_groovemanager_spi_asio_ASIOSampleRate_doubleValue
  (JNIEnv *, jobject);

/*
 * Class:     com_groovemanager_spi_asio_ASIOSampleRate
 * Method:    setValue
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_groovemanager_spi_asio_ASIOSampleRate_setValue
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
